import json
from typing import Dict, Any


class Product:
    """
    Represents a product in the Smart E-Commerce Price Optimization Tool.
    Includes attributes like price, demand, inventory, and methods for serialization/deserialization.
    """

    def __init__(self, product_id: str, name: str, price: float, demand: int, inventory: int):
        """
        Initialize a Product instance.

        :param product_id: Unique identifier for the product.
        :param name: Name of the product.
        :param price: Current price of the product.
        :param demand: Current demand for the product.
        :param inventory: Current inventory level for the product.
        """
        self.product_id = product_id
        self.name = name
        self.price = price
        self.demand = demand
        self.inventory = inventory

    def to_dict(self) -> Dict[str, Any]:
        """
        Serialize the Product instance to a dictionary.

        :return: Dictionary representation of the Product instance.
        """
        return {
            "product_id": self.product_id,
            "name": self.name,
            "price": self.price,
            "demand": self.demand,
            "inventory": self.inventory,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Product":
        """
        Deserialize a dictionary to a Product instance.

        :param data: Dictionary containing product data.
        :return: Product instance.
        """
        return cls(
            product_id=data["product_id"],
            name=data["name"],
            price=data["price"],
            demand=data["demand"],
            inventory=data["inventory"],
        )

    def to_json(self) -> str:
        """
        Serialize the Product instance to a JSON string.

        :return: JSON string representation of the Product instance.
        """
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> "Product":
        """
        Deserialize a JSON string to a Product instance.

        :param json_str: JSON string containing product data.
        :return: Product instance.
        """
        data = json.loads(json_str)
        return cls.from_dict(data)

    def update_price(self, new_price: float) -> None:
        """
        Update the price of the product.

        :param new_price: New price to set for the product.
        """
        if new_price < 0:
            raise ValueError("Price cannot be negative.")
        self.price = new_price

    def update_inventory(self, quantity: int) -> None:
        """
        Update the inventory level of the product.

        :param quantity: Quantity to add to the inventory (can be negative to reduce inventory).
        """
        new_inventory = self.inventory + quantity
        if new_inventory < 0:
            raise ValueError("Inventory cannot be negative.")
        self.inventory = new_inventory

    def calculate_revenue(self) -> float:
        """
        Calculate the revenue generated by the product based on price and demand.

        :return: Revenue generated by the product.
        """
        return self.price * self.demand

    def __repr__(self) -> str:
        """
        String representation of the Product instance.

        :return: String representation of the Product instance.
        """
        return f"Product(product_id={self.product_id}, name={self.name}, price={self.price}, demand={self.demand}, inventory={self.inventory})"