import json
from typing import Dict, Any, Optional
from datetime import datetime


class Product:
    """
    Represents a product in the Smart E-Commerce Price Optimization Tool.
    Includes attributes like price, demand, inventory, cost, and methods for analytics.
    """

    def __init__(self, product_id: str, name: str, price: float, demand: int, 
                 inventory: int, cost: Optional[float] = None, category: Optional[str] = None):
        """
        Initialize a Product instance.

        :param product_id: Unique identifier for the product.
        :param name: Name of the product.
        :param price: Current price of the product.
        :param demand: Current demand for the product.
        :param inventory: Current inventory level for the product.
        :param cost: Cost to acquire/produce the product (optional).
        :param category: Product category (optional).
        """
        self.product_id = product_id
        self.name = name
        self.price = price
        self.demand = demand
        self.inventory = inventory
        self.cost = cost if cost is not None else price * 0.6  # Default cost is 60% of price
        self.category = category
        self.created_at = datetime.now()
        self.updated_at = datetime.now()
        self.price_history = [{'price': price, 'timestamp': self.created_at.isoformat()}]

    def to_dict(self) -> Dict[str, Any]:
        """
        Serialize the Product instance to a dictionary.

        :return: Dictionary representation of the Product instance.
        """
        return {
            "product_id": self.product_id,
            "name": self.name,
            "price": self.price,
            "demand": self.demand,
            "inventory": self.inventory,
            "cost": self.cost,
            "category": self.category,
            "profit_margin": self.calculate_profit_margin(),
            "revenue": self.calculate_revenue(),
            "profit": self.calculate_profit(),
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Product":
        """
        Deserialize a dictionary to a Product instance.

        :param data: Dictionary containing product data.
        :return: Product instance.
        """
        return cls(
            product_id=data["product_id"],
            name=data["name"],
            price=data["price"],
            demand=data["demand"],
            inventory=data["inventory"],
            cost=data.get("cost"),
            category=data.get("category"),
        )

    def to_json(self) -> str:
        """
        Serialize the Product instance to a JSON string.

        :return: JSON string representation of the Product instance.
        """
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> "Product":
        """
        Deserialize a JSON string to a Product instance.

        :param json_str: JSON string containing product data.
        :return: Product instance.
        """
        data = json.loads(json_str)
        return cls.from_dict(data)

    def update_price(self, new_price: float) -> None:
        """
        Update the price of the product and record in history.

        :param new_price: New price to set for the product.
        """
        if new_price < 0:
            raise ValueError("Price cannot be negative.")
        if new_price < self.cost:
            raise ValueError(f"Price ${new_price} cannot be below cost ${self.cost}.")
        
        self.price = new_price
        self.updated_at = datetime.now()
        self.price_history.append({'price': new_price, 'timestamp': self.updated_at.isoformat()})

    def update_inventory(self, quantity: int) -> None:
        """
        Update the inventory level of the product.

        :param quantity: Quantity to add to the inventory (can be negative to reduce inventory).
        """
        new_inventory = self.inventory + quantity
        if new_inventory < 0:
            raise ValueError("Inventory cannot be negative.")
        self.inventory = new_inventory

    def calculate_revenue(self) -> float:
        """
        Calculate the revenue generated by the product based on price and demand.

        :return: Revenue generated by the product.
        """
        return self.price * self.demand
    
    def calculate_profit(self) -> float:
        """
        Calculate the profit generated by the product.

        :return: Profit generated by the product.
        """
        return (self.price - self.cost) * self.demand
    
    def calculate_profit_margin(self) -> float:
        """
        Calculate the profit margin as a percentage.

        :return: Profit margin as a percentage.
        """
        if self.price == 0:
            return 0.0
        return ((self.price - self.cost) / self.price) * 100
    
    def calculate_markup(self) -> float:
        """
        Calculate the markup percentage over cost.

        :return: Markup percentage.
        """
        if self.cost == 0:
            return 0.0
        return ((self.price - self.cost) / self.cost) * 100
    
    def is_profitable(self) -> bool:
        """
        Check if the product is currently profitable.

        :return: True if profitable, False otherwise.
        """
        return self.price > self.cost
    
    def calculate_inventory_value(self) -> float:
        """
        Calculate the total value of inventory at current price.

        :return: Total inventory value.
        """
        return self.price * self.inventory
    
    def calculate_inventory_cost(self) -> float:
        """
        Calculate the total cost of inventory.

        :return: Total inventory cost.
        """
        return self.cost * self.inventory
    
    def get_stock_status(self) -> str:
        """
        Get a human-readable stock status.

        :return: Stock status string.
        """
        if self.inventory == 0:
            return "out_of_stock"
        elif self.inventory < 10:
            return "low_stock"
        elif self.inventory < 50:
            return "moderate_stock"
        else:
            return "in_stock"
    
    def get_price_history(self) -> list:
        """
        Get the price change history.

        :return: List of price history entries.
        """
        return self.price_history

    def __repr__(self) -> str:
        """
        String representation of the Product instance.

        :return: String representation of the Product instance.
        """
        return (f"Product(product_id={self.product_id}, name={self.name}, "
                f"price=${self.price:.2f}, cost=${self.cost:.2f}, "
                f"margin={self.calculate_profit_margin():.1f}%, "
                f"demand={self.demand}, inventory={self.inventory})")